# This Github workflow updates the labels used in this repository

name: Labels Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
    paths: ./.github/labelsManifest.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: micnncim/action-label-syncer@v1 # Runs application that manages labels
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Uses token for secure access to repository
      with:
        manifest: ./.github/labelsManifest.yml # List of labels and the properties we want in our respository.